### ISSUE TITLE
XMP-dc VS XMP-pdf tags

### ISSUE THREAD

**Issue by ifohancroft** [glutanimate/PDFMtEd#23]
I am not disagreeing with the choice of XMP-dc tags over XMP-pdf tags, I am just curious.
Why did you choose to use XMP-dc tags over XMP-pdf tags?

**Comment by glutanimate** [comment]
Hey Ifo, That's a good question! It's been ages since, but looking at the docs for both specifications, I think it was for two reasons:

1. XMP-dc being used by epub's and me wanting to have a consistent metadata scheme for both
2. XMP-dc feeling slightly more suited for metadata in academic papers and other similar publications due to the field set-up

**Comment by ifohancroft** [comment]
Oh! Yeah, those are definitely good reasons. Also, when reading on XMP-pdf tags earlier, I noticed something that made me sort of uneasy about XMP-pdf tags (because I am not entirely sure which tags it applies to and when does it apply to them):

"The other tags are included because they have been observed in PDF files, **but some are avoided when writing due to name conflicts with other XMP namespaces**." from https://exiftool.org/TagNames/XMP.html#pdf

**Comment by ifohancroft** [comment]
I guess we can count this as resolved and close it.
