### ISSUE TITLE
Support for SVG

### ISSUE THREAD

**Issue by SecUpwN** [Glutanimate/PDFMtEd#3]
Hi @Glutanimate, first of all **HUGE THANKS** for continuing development of your awesome tool! :+1:

I am using it nearly on a daily basis, especially for [AIMSICD](https://secupwn.github.io/Android-IMSI-Catcher-Detector/). Since "marvelous Phil" (as you like to call him) refused to add SVG support and got even a little angry when asking him if he'd be officially moving to GitHub, here is my request: Would you please enable support to delete (or replace) all sensitive metadata from SVG files? I am looking for a convenient way to protect designer's privacy. Thank you!

**Comment by Glutanimate** [comment]
Hi,

thanks for taking the time to post a feature request. I am glad PDFMtEd turned out to be useful to you.

Adding support for a file format that's not editable by exiftool would require adding another back-end or devising a custom solution. Because PDFMtEd is only meant as a simple front-end to exiftool, this is outside of the scope of the project at the moment.

While I understand your frustration regarding your feature request against exiftool, I can also see why Phil would refuse to implement support for editing SVG files. With as many file formats as there are out there supporting all formats in their entirety is simply not feasible, and as a result some compromises will always need to be made.

Luckily you will be able to find alternatives for most file formats. [SVG Cleaner](http://qt-apps.org/content/show.php/SVG+Cleaner?content=147974) seems to be a good option for svg files, for instance.

In any case, I hope this was helpful. I'll be marking this feature request as "won't fix" for the time being.

Cheers
--Glutanimate

**Comment by SecUpwN** [comment]
Thanks for your clear words, @Glutanimate. Just for others reading this: [SVGCleaner on GitHub](https://github.com/RazrFalcon/SVGCleaner).
