### ISSUE TITLE
Switch to Metadata Anonymisation Toolkit?

### ISSUE THREAD

**Issue by SecUpwN** [Glutanimate/PDFMtEd#4]
Good morning @Glutanimate, just recently I discovered the [Metadata Anonymisation Toolkit](https://mat.boum.org/) which is included in [Tails](https://tails.boum.org/) and wondered how your script compares to it. The last changes on your repo happened in **2014**, thus I am not sure whether your script should be recommended to privacy advocates since it could be that the code is outdated and miss some important fields in files. How does your script compare to MAT in terms of safe matadata removal? Maybe you can update your scripts using the [MAT GIT](https://gitweb.torproject.org/user/jvoisin/mat.git)?

**Comment by Glutanimate** [comment]
Hi,

since the actual metadata editing is handled by exiftool I would suggest monitoring its [changelog](http://www.sno.phy.queensu.ca/~phil/exiftool/history.html) and [overview of supported file types](http://www.sno.phy.queensu.ca/~phil/exiftool/#supported) for any file types you are interested in. PDFMtEd will purge all metadata fields that are writable to exiftool. Keep your local installation of exiftool updated and the script will be able to handle anything supported by the latest exiftool release.

Reading through [this paper on MAT](http://arxiv.org/pdf/1212.3648.pdf) it looks like it does use exiftool for some file formats while relying on Hachoir and other libraries for others. For instance, MAT rerenders PDF files from scratch, thus eliminating metadata both in the file itself and embedded objects like images. This is something exiftool and, in turn, PDFMtEd can't do.

If privacy is your main concern and you want to make sure to "cover all possible bases" then I would recommend going with MAT instead of exiftool/PDFMtEd. As PDFMtEd was designed as a front-end to exiftool I don't plan on switching to MAT or any other back-end anytime soon.

Thanks for pointing me towards MAT, though. It's a very interesting project, indeed.

**Comment by jvoisin** [comment]
Thank you for reading my paper ♥

**Comment by Glutanimate** [comment]
Thanks for writing it! It was an enjoyable read on an interesting topic :thumbsup:.
